### ISSUE TITLE
Go Live Checklist!

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#103]
Application Review Checklist 

2020-10-02 

For use when releasing an application, adding major changes, or during an annual review.  

Checklist: 

- [x] Load Test #106
- [x] Google Analytics https://github.com/USGS-WiM/sw-flow-trends/issues/110 
- [x] If a WMA application, add to the WMA Internal Analytics page: https://github.com/USGS-VIZLAB/internal-analytics (see ReadMe)  (You can just make a pull request with changes to this yaml file: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/gaTable.yaml#L779 with whatever new IDs and views the dashboard should use for those applications.) https://github.com/USGS-WiM/sw-flow-trends/issues/110 
- [x] Configured for USA Analytics https://analytics.usa.gov/ https://github.com/USGS-WiM/sw-flow-trends/issues/110 

Browsers supported/not supported accounted for 
- [x] Microsoft Edge 
- [x] Internet Explorer 
- [x] Chrome (Desktop) 
- [x] Chrome (Android) 
- [x] Firefox 
- [x] Safari (iOS) 
- [x] Safari (OSX) 

Monitoring configured http://wim.usgs.gov/status/ 
- [x] Uptime Bot - https://github.com/USGS-WiM/wim-infrastructure/wiki/Monitoring-with-Uptimebot-and-FGDC-status-checker 
- [x] FGDC status-checker (just update the xml wimMapServices: https://github.com/USGS-WiM/service_lists/tree/master/mapServices_xml ) 
- [x] Infrastructure reviewed/documented - https://github.com/USGS-WiM/sw-flow-trends/issues/104
- [x] https:// enabled 
- [x] Backups enabled 
- [x] (ArcServer) Map Services are tuned 
- [x] A&A requirements reviewed/documented 
- [x] GitHub repo configured.  
- [x] Version tags implemented.  https://github.com/USGS-WiM/sw-flow-trends/issues/105
- [x] Follows guidelines established by WimPo 

Application Requirements: 
- [x] Favicon https://github.com/USGS-WiM/sw-flow-trends/issues/106
- [x] About page credits libraries/partners appropriately 
- [x] Any 3rd party license disclaimers we need to include 
- [x] Public web/map service URLs are given somewhere in the interface/documentation 
- [x] Current version displayed in application 
- [x] For interactive Maps, have Erik do a cartographic review 
- [x] Appropriate USGS disclaimers https://www2.usgs.gov/fsp/fsp_disclaimers.asp  https://github.com/USGS-WiM/sw-flow-trends/issues/107
- [x] (If initial release, or substantial upgrade) Has USGS Communications (or WSC Communications) been engaged to announce the release of a new product/feature? 
- [x] Featured on WIM Website - https://wim.usgs.gov/#/projects 
- [x] Review for WIM branding (watch out for “WiM”) https://github.com/USGS-WiM/sw-flow-trends/issues/108
- [x] Is the documentation in wimfo for this app/project up-to-date? https://github.com/USGS-WiM/sw-flow-trends/issues/109
- [x] Do we meet the USGS release standards for this application? https://www2.usgs.gov/usgs-manual/im/IM-OSQI-2016-01.html 

Web standards https://www2.usgs.gov/usgs-manual/600/601-1.html 
- [x] 508 Compliance 
- [x] All required Metadata https://github.com/USGS-WiM/sw-flow-trends/issues/106 
- [x] IPDS Approval Process complete 
- [x] DOI numbers issued 
- [x] Author(s) profile page updated 
https://github.com/usgs/best-practices/blob/master/doi.md 

References: 

Reference: https://github.com/usgs/best-practices

**Comment by HansVraga** [comment]
508 Compliance sought after with styling. ANDI and CCA tools are referenced.

**Comment by HansVraga** [comment]
Checking off IPDS / DOI / Author update to be part of a conversation with the cooperators and joint effort with the other nawqatrends applications

**Comment by HansVraga** [comment]
https://github.com/USGS-WiM/sw-flow-trends/issues/110
